#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : lsd
Version  : 0.17.0
Release  : 1
URL      : file:///insilications/build/clearlinux/packages/lsd/lsd-0.17.0.zip
Source0  : file:///insilications/build/clearlinux/packages/lsd/lsd-0.17.0.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: lsd-bin = %{version}-%{release}
Requires: lsd-data = %{version}-%{release}
Requires: time
BuildRequires : rustc
BuildRequires : time
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# LSD (LSDeluxe)
[![license](http://img.shields.io/badge/license-Apache%20v2-orange.svg)](https://raw.githubusercontent.com/Peltoche/ical-rs/master/LICENSE)
[![Latest version](https://img.shields.io/crates/v/lsd.svg)](https://crates.io/crates/lsd)

%package bin
Summary: bin components for the lsd package.
Group: Binaries
Requires: lsd-data = %{version}-%{release}

%description bin
bin components for the lsd package.


%package data
Summary: data components for the lsd package.
Group: Data

%description data
data components for the lsd package.


%prep
%setup -q -n lsd-0.17.0
cd %{_builddir}/lsd-0.17.0

%build
unset http_proxy
unset https_proxy
unset no_proxy
RUSTFLAGS="-C target-cpu=native"
cargo update

%install
RUSTFLAGS="-C target-cpu=native"
RUSTFLAGS="-C target-cpu=native" cargo install --no-track --all-features --path . --root %{buildroot}/usr/
## install_append content
# shell completion for bash
install -dm 0755 %{buildroot}/usr/share/bash-completion/completions
install -m0644 ./target/release/build/lsd-*/out/lsd.bash %{buildroot}/usr/share/bash-completion/completions/lsd
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lsd

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/lsd
